---
- name: tomcat install
  hosts: localhost
  become: true
  tasks:
    - include_vars: in_var.yml
    - name: Installing {{ packages }} on {{ hostname }}
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Clone a github repository
      git:
       repo: https://github.com/sqlite/sqlite.git
       clone: yes
       update: yes

    - name: download tomcat server packages
      get_url:
      url: wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
    
    - name: start tomcat services
      shell: chmod +x cloud_sql_proxy

    - name: download tomcat server packages
      get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
      dest: /opt
      
    - name: extract tomcat packages
      unarchive:
        src: /opt/apache-tomcat-9.0.54.tar.gz
        dest: /opt
        remote_src: yes

    - name: start tomcat services
      shell: nohup /opt/apache-tomcat-9.0.54/bin/startup.sh
