---
- name: tomcat install
  hosts: localhost
  become: true
  vars_files:
     - tomcat_vars
    
  tasks:
    - name: Installing {{ packages }} on {{ hostname }}
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
    - name: Clone a github repository
      git:
       repo: https://github.com/sravan-github/Java_regist_app.git
       dest: /home/sravangcp/java/
       clone: yes
       update: yes
    - name: download tomcat server packages
      shell: wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
    
    - name: start tomcat services
      shell: chmod +x cloud_sql_proxy

    - name: download tomcat server packages
      get_url:
        url: {{ tomcat_url }}
        dest: /opt
      
    - name: extract tomcat packages
      unarchive:
        src: /opt/{{ tomcat_package }}.tar.gz
        dest: /opt
        remote_src: yes
    - name: start tomcat services
      shell: nohup /opt/{{ tomcat_package }}/bin/startup.sh
